CREATE DATABASE Velcro;

use Velcro;

CREATE TABLE Users(
  UserID int UNIQUE NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL
);


CREATE TABLE Products(
  ProductID int UNIQUE NOT NULL AUTO_INCREMENT,
  ProductName VARCHAR(512) NOT NULL,
  ProductPage VARCHAR(512) NOT NULL,
  ProductImage VARCHAR(512) NOT NULL,
  Vendor VARCHAR(512) NOT NULL,
  Region VARCHAR(512) NOT NULL
);