CREATE TABLE Users(
  UserID int UNIQUE NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(512) NOT NULL,
  LastName VARCHAR(512) NOT NULL,
  Email VARCHAR(512) UNIQUE NOT NULL,
  Password VARCHAR(512) NOT NULL
);